### ISSUE TITLE
[People] Nenets, Russia

### ISSUE THREAD

**Issue by tchret** [bitstein/justmeat.co#15]
https://en.wikipedia.org/wiki/Nenets_people

http://www.washingtonpost.com/wp-dyn/content/article/2008/05/13/AR2008051300583.html?sid=ST2008051302252&noredirect=on

> In this case it would be the Nenet paradox. The Nenets, the indigenous reindeer-herding people of this part of Siberia, have a menu that sounds like just the opposite of what the doctor ordered: They eat reindeer meat, most of it raw and frozen. From September to May they eat very little else, apart from the odd piece of raw, preferably frozen, fish. One would think that this extreme protein- and fat-driven diet would lead to a lot of health problems -- obesity, cardiovascular diseases -- but the opposite is true.

> "It is my experience that the further away you come from the city centers of the Arctic, the healthier people look," says Lars Kullerud, president of the University of the Arctic, a network of more than 100 universities and colleges. He researches the diets of the region's indigenous people.

**Comment by bitstein** [comment]
Great suggestion, thank you.
